class Url < ActiveHash::Base
  self.data= [
    {id: "#", name: '------------------'},
    {id: "https://www.pref.okinawa.jp/otoiawase.html", name: '沖縄県庁' },
    {id: "https://www.info.city.naha.okinawa.jp/index.html", name: '那覇市役所'},
    {id: "https://www.city.okinawa.okinawa.jp/inquiry/", name: '沖縄市役所'},
    {id: "https://www.city.uruma.lg.jp/inquiry/", name: 'うるま市役所'},
    {id: "https://www.city.urasoe.lg.jp/contact/goiken", name: '浦添市役所'},
    {id: "https://www.city.ginowan.lg.jp/cgi-bin/inquiry.php/161?page_no=5156", name: '宜野湾市役所'},
    {id: "http://www.city.nago.okinawa.jp/contact.html", name: '名護市役所'},
    {id: "https://www.city.itoman.lg.jp/mailform/acc.cgi?id=135987550318977", name: '糸満市役所'},
    {id: "https://www.city.tomigusuku.lg.jp/sp/contact/org:20/", name: '豊見城市役所'},
    {id: "https://www.city.miyakojima.lg.jp/inquiry/request.html", name: '宮古島市役所'},
    {id: "https://www.city.ishigaki.okinawa.jp/contact.html", name: '石垣市役所'},
    {id: "https://www.city.nanjo.okinawa.jp/contact/", name: '南城市役所'},
    {id: "https://www.vill.yomitan.okinawa.jp/contact/", name: '読谷村役場'},
    {id: "https://www.town.haebaru.lg.jp/docs/2013022800440/", name: '南風原町役場'},
    {id: "http://www.town.nishihara.okinawa.jp/mail/contact/jform.php", name: '西原町役場'},
    {id: "http://www.chatan.jp/choseijoho/sodan.html", name: '北谷町役場'},
    {id: "https://www.town.yaese.lg.jp/docs/2014032000080/", name: '八重瀬町役場'},
    {id: "https://secure.iamdn.co.jp/www.vill.nakagusuku.okinawa.jp/index.jsp?cd=00", name: '中城村役場'},
    {id: "http://www.town.yonabaru.okinawa.jp/kakukka/", name: '与那原町役場'},
    {id: "https://www.vill.kitanakagusuku.lg.jp/kakuka/soumu/jouhou/800.html", name: '北中城村役場'},
    {id: "http://www.town.motobu.okinawa.jp/access#02", name: '元部役場'},
    {id: "http://www.town.kadena.okinawa.jp/departments/kak259.html", name: '嘉手納町役場'},
    {id: "https://www.town.kin.okinawa.jp/contact/", name: '金武町役場'},
    {id: "https://www.vill.onna.okinawa.jp/contact/", name: '恩納村役場'},
    {id: "https://www.nakijin.jp/pagtop/kakuka/somuka/index.html", name: '今帰仁村役場'},
    {id: "http://www.town.kumejima.okinawa.jp/docs/2017071200015/", name: '久米島町役場'},
    {id: "http://www.vill.ginoza.okinawa.jp/faq", name: '宜野座村役場'},
    {id: "http://www.vill.kunigami.okinawa.jp/category/k_soumu/", name: '国頭村役場'},
    {id: "https://www.iejima.org/inquiry/", name: '伊江村役場'},
    {id: "https://www.town.taketomi.lg.jp/contact/", name: '竹富町役場'},
    {id: "http://www.vill.ogimi.okinawa.jp/docs/2014031400010/", name: '大宣味村役場'},
    {id: "http://www.vill.higashi.okinawa.jp/mailform.jsp", name: '東村役場'},
    {id: "https://www.town.yonaguni.okinawa.jp/docs/2018080700015/", name: '与那国町役場'},
    {id: "https://vill.izena.okinawa.jp/contact/", name: '伊是名村役場'},
    {id: "http://www.vill.minamidaito.okinawa.jp/link.html", name: '南大東村役場'},
    {id: "http://www.vill.iheya.okinawa.jp/mailform.jsp", name: '伊平屋村役場'},
    {id: "http://www.vill.tarama.okinawa.jp/?p=300", name: '多良間村役場'},
    {id: "https://www.vill.zamami.okinawa.jp/info/contact.html", name: '座間味村役場'},
    {id: "http://www.vill.aguni.okinawa.jp/modules/weblinks/", name: '粟国村役場'},
    {id: "http://www.vill.tokashiki.okinawa.jp/%E3%81%8A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B-2", name: '渡嘉敷村役場'},
    {id: "http://vill.kitadaito.okinawa.jp/index.php?id=30", name: '北大東島役場'},
    {id: "http://www.vill.tonaki.okinawa.jp/mailform.jsp", name: '渡名喜村役場'} 
  ]

  include ActiveHash::Associations
  has_many :memos
end
